//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ZespolRProject.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Answ
    {
        public int a_id { get; set; }
        public Nullable<int> a_test { get; set; }
        public Nullable<int> a_ques { get; set; }
        public Nullable<int> a_cand { get; set; }
        public string a_answ { get; set; }
    }
}
