//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ZespolRProject.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Editor
    {
        public int ed_id { get; set; }
        public string ed_name { get; set; }
        public string ed_surname { get; set; }
        public Nullable<int> ed_phone { get; set; }
        public Nullable<int> ed_def_lng { get; set; }
        public string ed_password { get; set; }
        public Nullable<int> ed_mod { get; set; }
    }
}
