//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ZespolRProject.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Language
    {
        public Language()
        {
            this.Candidate = new HashSet<Candidate>();
            this.Editor = new HashSet<Editor>();
            this.Test = new HashSet<Test>();
            this.TestVersion = new HashSet<TestVersion>();
        }
    
        public int lng_id { get; set; }
        public string lng_name { get; set; }
    
        public virtual ICollection<Candidate> Candidate { get; set; }
        public virtual ICollection<Editor> Editor { get; set; }
        public virtual ICollection<Test> Test { get; set; }
        public virtual ICollection<TestVersion> TestVersion { get; set; }
    }
}
