//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ZespolRProject.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TestTake
    {
        public int tt_id { get; set; }
        public Nullable<int> tt_tv { get; set; }
        public Nullable<int> tt_ca { get; set; }
        public Nullable<System.DateTime> tt_start { get; set; }
        public Nullable<System.DateTime> tt_end { get; set; }
        public Nullable<int> tt_status { get; set; }
    }
}
