//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ZespolRProject.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Test
    {
        public int t_id { get; set; }
        public string t_name { get; set; }
        public string t_desc { get; set; }
        public Nullable<int> t_po { get; set; }
        public Nullable<int> t_def_lng { get; set; }
        public Nullable<int> t_ed { get; set; }
        public Nullable<System.DateTime> t_start { get; set; }
        public Nullable<System.DateTime> t_end { get; set; }
        public Nullable<bool> t_is_published { get; set; }
        public Nullable<int> t_tt_limit { get; set; }
        public Nullable<decimal> t_pass_limit { get; set; }
        public Nullable<System.TimeSpan> t_time_limit { get; set; }
    }
}
