//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ZespolRProject.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tt_a_assoc
    {
        public int ID { get; set; }
        public Nullable<int> C_tt { get; set; }
        public Nullable<int> C_a { get; set; }
        public Nullable<System.DateTime> C_time { get; set; }
    }
}
