//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ZespolRProject.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class zespolrEntities2 : DbContext
    {
        public zespolrEntities2()
            : base("name=zespolrEntities2")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<Answer> Answer { get; set; }
        public DbSet<Candidate> Candidate { get; set; }
        public DbSet<Editor> Editor { get; set; }
        public DbSet<Language> Language { get; set; }
        public DbSet<Moderator> Moderator { get; set; }
        public DbSet<Position> Position { get; set; }
        public DbSet<Question> Question { get; set; }
        public DbSet<QuestionType> QuestionType { get; set; }
        public DbSet<sysdiagrams> sysdiagrams { get; set; }
        public DbSet<Test> Test { get; set; }
        public DbSet<TestTake> TestTake { get; set; }
        public DbSet<TestTakeStatus> TestTakeStatus { get; set; }
        public DbSet<TestVersion> TestVersion { get; set; }
        public DbSet<tt_a_assoc> tt_a_assoc { get; set; }
    }
}
