//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ZespolR.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Editor
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Editor()
        {
            this.Test = new HashSet<Test>();
        }
    
        public int ed_id { get; set; }
        public string ed_name { get; set; }
        public string ed_surname { get; set; }
        public Nullable<int> ed_phone { get; set; }
        public Nullable<int> ed_def_lng { get; set; }
        public string ed_password { get; set; }
        public Nullable<int> ed_mod { get; set; }
    
        public virtual Language Language { get; set; }
        public virtual Moderator Moderator { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Test> Test { get; set; }
    }
}
