//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ZespolR.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TestTake
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TestTake()
        {
            this.tt_a_assoc = new HashSet<tt_a_assoc>();
        }
    
        public int tt_id { get; set; }
        public Nullable<int> tt_tv { get; set; }
        public Nullable<int> tt_ca { get; set; }
        public Nullable<System.DateTime> tt_start { get; set; }
        public Nullable<System.DateTime> tt_end { get; set; }
        public Nullable<int> tt_status { get; set; }
    
        public virtual Candidate Candidate { get; set; }
        public virtual TestTakeStatus TestTakeStatus { get; set; }
        public virtual TestVersion TestVersion { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tt_a_assoc> tt_a_assoc { get; set; }
    }
}
