//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ZespolR.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TestVersion
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TestVersion()
        {
            this.TestTake = new HashSet<TestTake>();
        }
    
        public int tv_id { get; set; }
        public Nullable<int> tv_t { get; set; }
        public Nullable<int> tv_lng { get; set; }
        public Nullable<bool> tv_is_published { get; set; }
    
        public virtual Language Language { get; set; }
        public virtual Test Test { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TestTake> TestTake { get; set; }
    }
}
